#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import sys
from pathlib import Path

# 颜色定义
class Colors:
    GREEN = '\033[0;32m'
    BLUE = '\033[0;34m'
    YELLOW = '\033[1;33m'
    RED = '\033[0;31m'
    NC = '\033[0m'  # No Color

def print_colored(text, color=Colors.NC):
    print(f"{color}{text}{Colors.NC}")

def create_project_structure(project_name):
    """创建项目文件夹结构"""
    project_path = Path(project_name)
    
    # 检查项目是否已存在
    if project_path.exists():
        print_colored(f"警告: 项目文件夹 '{project_name}' 已存在", Colors.YELLOW)
        response = input("是否继续? (y/n): ")
        if response.lower() != 'y':
            print_colored("操作已取消", Colors.RED)
            sys.exit(1)
    
    # 创建文件夹结构
    dirs = [
        project_path / "src",
        project_path / "include",
        project_path / ".vscode"
    ]
    
    for dir_path in dirs:
        dir_path.mkdir(parents=True, exist_ok=True)
        print_colored(f"✓ 创建文件夹: {dir_path}", Colors.GREEN)
    
    return project_path

def create_tasks_json(project_path):
    """创建 tasks.json"""
    tasks_content = '''{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "shell",
      "label": "C/C++: g++ build active file",
      "command": "/usr/bin/g++",
      "args": [
        "-g",
        "${file}",
        "-o",
        "${fileDirname}/${fileBasenameNoExtension}",
        "-I${workspaceFolder}/include"
      ],
      "options": {
        "cwd": "${fileDirname}"
      },
      "problemMatcher": ["$gcc"],
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "detail": "Task generated by Debugger."
    },
    {
      "type": "shell",
      "label": "C/C++: g++ build project",
      "command": "/usr/bin/g++",
      "args": [
        "-g",
        "${workspaceFolder}/src/*.cpp",
        "-o",
        "${workspaceFolder}/${workspaceFolderBasename}",
        "-I${workspaceFolder}/include",
        "-std=c++17"
      ],
      "options": {
        "cwd": "${workspaceFolder}"
      },
      "problemMatcher": ["$gcc"],
      "group": "build",
      "detail": "Build all source files in the project"
    }
  ]
}
'''
    tasks_file = project_path / ".vscode" / "tasks.json"
    tasks_file.write_text(tasks_content, encoding='utf-8')
    print_colored(f"✓ 创建文件: {tasks_file}", Colors.GREEN)

def create_launch_json(project_path, project_name):
    """创建 launch.json"""
    launch_content = f'''{{
  "version": "0.2.0",
  "configurations": [
    {{
      "name": "C/C++: g++ build and debug active file",
      "type": "cppdbg",
      "request": "launch",
      "program": "${{fileDirname}}/${{fileBasenameNoExtension}}",
      "args": [],
      "stopAtEntry": false,
      "cwd": "${{workspaceFolder}}",
      "environment": [],
      "externalConsole": false,
      "MIMode": "gdb",
      "miDebuggerPath": "/usr/bin/gdb",
      "setupCommands": [
        {{
          "description": "Enable pretty-printing for gdb",
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
        }},
        {{
          "description": "Set Disassembly Flavor to Intel",
          "text": "-gdb-set disassembly-flavor intel",
          "ignoreFailures": true
        }}
      ],
      "preLaunchTask": "C/C++: g++ build active file"
    }},
    {{
      "name": "C/C++: g++ build and debug project",
      "type": "cppdbg",
      "request": "launch",
      "program": "${{workspaceFolder}}/{project_name}",
      "args": [],
      "stopAtEntry": false,
      "cwd": "${{workspaceFolder}}",
      "environment": [],
      "externalConsole": false,
      "MIMode": "gdb",
      "miDebuggerPath": "/usr/bin/gdb",
      "setupCommands": [
        {{
          "description": "Enable pretty-printing for gdb",
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
        }}
      ],
      "preLaunchTask": "C/C++: g++ build project"
    }}
  ]
}}
'''
    launch_file = project_path / ".vscode" / "launch.json"
    launch_file.write_text(launch_content, encoding='utf-8')
    print_colored(f"✓ 创建文件: {launch_file}", Colors.GREEN)

def create_c_cpp_properties_json(project_path):
    """创建 c_cpp_properties.json"""
    cpp_properties_content = '''{
  "configurations": [
    {
      "name": "Linux",
      "includePath": [
        "${workspaceFolder}/**",
        "${workspaceFolder}/include"
      ],
      "defines": [],
      "compilerPath": "/usr/bin/gcc",
      "cStandard": "c11",
      "cppStandard": "c++17",
      "intelliSenseMode": "linux-gcc-x64",
      "configurationProvider": "ms-vscode.cmake-tools"
    }
  ],
  "version": 4
}
'''
    cpp_properties_file = project_path / ".vscode" / "c_cpp_properties.json"
    cpp_properties_file.write_text(cpp_properties_content, encoding='utf-8')
    print_colored(f"✓ 创建文件: {cpp_properties_file}", Colors.GREEN)

def create_main_cpp(project_path):
    """创建示例 main.cpp"""
    main_cpp_content = '''#include <iostream>
#include <vector>
#include <string>
#include "main.h"

using namespace std;

int main()
{
    vector<string> msg {"Hello", "C++", "World", "from", "VS Code", "and the C++ extension!"};

    for (const string& word : msg)
    {
        cout << word << " ";
    }
    cout << endl;

    return 0;
}
'''
    main_cpp_file = project_path / "src" / "main.cpp"
    main_cpp_file.write_text(main_cpp_content, encoding='utf-8')
    print_colored(f"✓ 创建文件: {main_cpp_file}", Colors.GREEN)

def create_main_h(project_path):
    """创建示例 main.h"""
    main_h_content = '''#pragma once

#include <string>
#include <vector>

// 示例函数声明
std::string greet();
void printMessage(const std::string& msg);
'''
    main_h_file = project_path / "include" / "main.h"
    main_h_file.write_text(main_h_content, encoding='utf-8')
    print_colored(f"✓ 创建文件: {main_h_file}", Colors.GREEN)

def create_readme(project_path, project_name):
    """创建 README.md"""
    readme_content = f'''# {project_name}

C++ 项目

## 项目结构

```
{project_name}/
├── .vscode/          # VSCode 配置文件
│   ├── tasks.json    # 构建任务配置
│   ├── launch.json   # 调试配置
│   └── c_cpp_properties.json  # IntelliSense 配置
├── include/          # 头文件目录
│   └── main.h
├── src/              # 源代码目录
│   └── main.cpp
└── README.md
```

## 使用方法

1. 在 VSCode 中打开项目文件夹
2. 按 `F5` 或点击播放按钮进行调试
3. 按 `Ctrl+Shift+B` 进行构建

## 编译和运行

### 使用 VSCode 任务
- 构建活动文件: `Ctrl+Shift+B` (选择 "C/C++: g++ build active file")
- 构建整个项目: `Ctrl+Shift+B` (选择 "C/C++: g++ build project")

### 使用命令行
```bash
# 编译单个文件
g++ -g src/main.cpp -o main -Iinclude

# 运行
./main
```

## 调试

1. 在代码中设置断点（点击行号左侧）
2. 按 `F5` 开始调试
3. 使用调试控制面板进行单步调试
'''
    readme_file = project_path / "README.md"
    readme_file.write_text(readme_content, encoding='utf-8')
    print_colored(f"✓ 创建文件: {readme_file}", Colors.GREEN)

def main():
    print_colored("=" * 40, Colors.BLUE)
    print_colored("  VSCode C++ 项目创建工具", Colors.BLUE)
    print_colored("=" * 40, Colors.BLUE)
    print()
    
    # 获取项目名称
    if len(sys.argv) > 1:
        project_name = sys.argv[1]
    else:
        project_name = input("请输入项目名称: ").strip()
    
    if not project_name:
        print_colored("错误: 项目名称不能为空", Colors.RED)
        sys.exit(1)
    
    print()
    print_colored("正在创建项目结构...", Colors.BLUE)
    print()
    
    # 创建项目结构
    project_path = create_project_structure(project_name)
    
    # 创建配置文件
    create_tasks_json(project_path)
    create_launch_json(project_path, project_name)
    create_c_cpp_properties_json(project_path)
    
    # 创建示例文件
    create_main_cpp(project_path)
    create_main_h(project_path)
    create_readme(project_path, project_name)
    
    print()
    print_colored(f"✓ 项目 '{project_name}' 创建成功!", Colors.GREEN)
    print()
    print_colored("项目结构:", Colors.BLUE)
    
    # 显示项目结构
    for root, dirs, files in os.walk(project_path):
        level = root.replace(str(project_path), '').count(os.sep)
        indent = ' ' * 2 * level
        print(f"{indent}{os.path.basename(root)}/")
        subindent = ' ' * 2 * (level + 1)
        for file in files:
            print(f"{subindent}{file}")
    
    print()
    print_colored("下一步:", Colors.YELLOW)
    print(f"  1. cd {project_name}")
    print("  2. code .")
    print()

if __name__ == "__main__":
    main()

