#!/bin/bash

# 颜色定义
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  VSCode C++ 项目创建工具${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# 获取项目名称（支持命令行参数）
if [ -n "$1" ]; then
    PROJECT_NAME="$1"
else
    read -p "请输入项目名称: " PROJECT_NAME
fi

if [ -z "$PROJECT_NAME" ]; then
    echo -e "${YELLOW}错误: 项目名称不能为空${NC}"
    exit 1
fi

# 检查项目是否已存在
if [ -d "$PROJECT_NAME" ]; then
    echo -e "${YELLOW}警告: 项目文件夹 '$PROJECT_NAME' 已存在${NC}"
    read -p "是否继续? (y/n): " CONTINUE
    if [ "$CONTINUE" != "y" ] && [ "$CONTINUE" != "Y" ]; then
        exit 1
    fi
fi

# 创建项目文件夹结构
echo -e "${GREEN}正在创建项目结构...${NC}"
mkdir -p "$PROJECT_NAME"/{src,include,.vscode}

# 创建 .vscode/tasks.json
cat > "$PROJECT_NAME/.vscode/tasks.json" << 'EOF'
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "shell",
      "label": "C/C++: g++ build active file",
      "command": "/usr/bin/g++",
      "args": [
        "-g",
        "${file}",
        "-o",
        "${fileDirname}/${fileBasenameNoExtension}",
        "-I${workspaceFolder}/include"
      ],
      "options": {
        "cwd": "${fileDirname}"
      },
      "problemMatcher": ["$gcc"],
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "detail": "Task generated by Debugger."
    },
    {
      "type": "shell",
      "label": "C/C++: g++ build project",
      "command": "/usr/bin/g++",
      "args": [
        "-g",
        "${workspaceFolder}/src/*.cpp",
        "-o",
        "${workspaceFolder}/${workspaceFolderBasename}",
        "-I${workspaceFolder}/include",
        "-std=c++17"
      ],
      "options": {
        "cwd": "${workspaceFolder}"
      },
      "problemMatcher": ["$gcc"],
      "group": "build",
      "detail": "Build all source files in the project"
    }
  ]
}
EOF

# 创建 .vscode/launch.json
cat > "$PROJECT_NAME/.vscode/launch.json" << EOF
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "C/C++: g++ build and debug active file",
      "type": "cppdbg",
      "request": "launch",
      "program": "\${fileDirname}/\${fileBasenameNoExtension}",
      "args": [],
      "stopAtEntry": false,
      "cwd": "\${workspaceFolder}",
      "environment": [],
      "externalConsole": false,
      "MIMode": "gdb",
      "miDebuggerPath": "/usr/bin/gdb",
      "setupCommands": [
        {
          "description": "Enable pretty-printing for gdb",
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
        },
        {
          "description": "Set Disassembly Flavor to Intel",
          "text": "-gdb-set disassembly-flavor intel",
          "ignoreFailures": true
        }
      ],
      "preLaunchTask": "C/C++: g++ build active file"
    },
    {
      "name": "C/C++: g++ build and debug project",
      "type": "cppdbg",
      "request": "launch",
      "program": "\${workspaceFolder}/$PROJECT_NAME",
      "args": [],
      "stopAtEntry": false,
      "cwd": "\${workspaceFolder}",
      "environment": [],
      "externalConsole": false,
      "MIMode": "gdb",
      "miDebuggerPath": "/usr/bin/gdb",
      "setupCommands": [
        {
          "description": "Enable pretty-printing for gdb",
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
        }
      ],
      "preLaunchTask": "C/C++: g++ build project"
    }
  ]
}
EOF

# 创建 .vscode/c_cpp_properties.json
cat > "$PROJECT_NAME/.vscode/c_cpp_properties.json" << EOF
{
  "configurations": [
    {
      "name": "Linux",
      "includePath": [
        "\${workspaceFolder}/**",
        "\${workspaceFolder}/include"
      ],
      "defines": [],
      "compilerPath": "/usr/bin/gcc",
      "cStandard": "c11",
      "cppStandard": "c++17",
      "intelliSenseMode": "linux-gcc-x64",
      "configurationProvider": "ms-vscode.cmake-tools"
    }
  ],
  "version": 4
}
EOF

# 创建示例 main.cpp
cat > "$PROJECT_NAME/src/main.cpp" << 'EOF'
#include <iostream>
#include <vector>
#include <string>
#include "main.h"

using namespace std;

int main()
{
    vector<string> msg {"Hello", "C++", "World", "from", "VS Code", "and the C++ extension!"};

    for (const string& word : msg)
    {
        cout << word << " ";
    }
    cout << endl;

    return 0;
}
EOF

# 创建示例头文件
cat > "$PROJECT_NAME/include/main.h" << 'EOF'
#pragma once

#include <string>
#include <vector>

// 示例函数声明
std::string greet();
void printMessage(const std::string& msg);
EOF

# 创建 README.md
cat > "$PROJECT_NAME/README.md" << EOF
# $PROJECT_NAME

C++ 项目

## 项目结构

\`\`\`
$PROJECT_NAME/
├── .vscode/          # VSCode 配置文件
│   ├── tasks.json    # 构建任务配置
│   ├── launch.json   # 调试配置
│   └── c_cpp_properties.json  # IntelliSense 配置
├── include/          # 头文件目录
│   └── main.h
├── src/              # 源代码目录
│   └── main.cpp
└── README.md
\`\`\`

## 使用方法

1. 在 VSCode 中打开项目文件夹
2. 按 \`F5\` 或点击播放按钮进行调试
3. 按 \`Ctrl+Shift+B\` 进行构建

## 编译和运行

### 使用 VSCode 任务
- 构建活动文件: \`Ctrl+Shift+B\` (选择 "C/C++: g++ build active file")
- 构建整个项目: \`Ctrl+Shift+B\` (选择 "C/C++: g++ build project")

### 使用命令行
\`\`\`bash
# 编译单个文件
g++ -g src/main.cpp -o main -Iinclude

# 运行
./main
\`\`\`

## 调试

1. 在代码中设置断点（点击行号左侧）
2. 按 \`F5\` 开始调试
3. 使用调试控制面板进行单步调试
EOF

echo ""
echo -e "${GREEN}✓ 项目 '$PROJECT_NAME' 创建成功!${NC}"
echo ""
echo -e "${BLUE}项目结构:${NC}"
tree -L 2 "$PROJECT_NAME" 2>/dev/null || find "$PROJECT_NAME" -type f -o -type d | head -20
echo ""
echo -e "${YELLOW}下一步:${NC}"
echo -e "  1. cd $PROJECT_NAME"
echo -e "  2. code ."
echo ""

